-- 코드를 입력하세요
# SELECT DATETIME
#   FROM (
#      SELECT DATETIME, 
#             ROW_NUMBER() OVER(ORDER BY DATETIME DESC) AS RN
#        FROM ANIMAL_INS
#   ) SUB
#   WHERE RN = 1;
  
# SELECT DATETIME
#   FROM ANIMAL_INS
#  ORDER BY DATETIME DESC
#  LIMIT 1;
 
 SELECT MAX(DATETIME) AS Latest_DateTime
  FROM ANIMAL_INS;